ALTER TABLE allergens RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE allergens RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE ingredients RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE ingredients RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE instructions RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE instructions RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE recipe_nutrition RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE recipe_nutrition RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE recipes RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE recipes RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE units RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE units RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE users RENAME COLUMN `clerkId` TO `clerk_id`;
ALTER TABLE users RENAME COLUMN `createdAt` TO `created_at`;
ALTER TABLE users RENAME COLUMN `updatedAt` TO `updated_at`;
ALTER TABLE recipes ADD `slug` varchar(255) NOT NULL;
CREATE INDEX recipes__slug__index ON recipes (`slug`);
CREATE UNIQUE INDEX recipes__slug__unique_index ON recipes (`slug`);
CREATE INDEX created_at__index ON recipes (`created_at`);
CREATE INDEX users__username__index ON users (`username`);
CREATE UNIQUE INDEX users__username__unique_index ON users (`username`);
CREATE UNIQUE INDEX users__email__index ON users (`email`);
CREATE INDEX users__created_at__index ON users (`created_at`);